apiVersion: nats.crossplane.io/v1alpha1
kind: Stream
metadata:
  name: unicorn
spec:
  forProvider:
    config:
      subjects:
        - unicorn.>
      retention: Limits
      storage: File
      maxBytes: 102400
      maxConsumers: -1
      maxMsgs: -1
      discard: Old
  providerConfigRef:
    name: acc1
