apiVersion: stream.nats.crossplane.io/v1alpha1
kind: Stream
metadata:
  name: aggregate
  annotations:
    crossplane.io/external-name: aggregate
spec:
  forProvider:
    config:
      name: aggregate
      retention: Limits
      storage: File
      maxBytes: 204800
      discard: DiscardOld
      sources:
        - name: source
          external:
            apiPrefix: "$JS.foo.API"
            deliverPrefix: ""
        - name: source
          external:
            apiPrefix: "$JS.both.API"
            deliverPrefix: ""
        - name: source
          external:
            apiPrefix: "$JS.missing.API"
            deliverPrefix: ""
  providerConfigRef:
    name: acc1
