//go:build generate
// +build generate

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// NOTE: See the below link for details on what is happening here.
// https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

// Remove existing CRDs
//go:generate rm -rf ../package/crds

// Generate deepcopy methodsets and CRD manifests
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../hack/boilerplate.go.txt paths=./... crd:crdVersions=v1 output:artifacts:config=../package/crds

// Generate crossplane-runtime methodsets (resource.Claim, etc)
//go:generate go run -tags generate github.com/crossplane/crossplane-tools/cmd/angryjet generate-methodsets --header-file=../hack/boilerplate.go.txt ./...

// Generate clientset for types.
//go:generate rm -rf ../internal/clientset
//go:generate go run -tags generate k8s.io/code-generator/cmd/client-gen --clientset-name "provider" --build-tag="ignore_autogenerated" --go-header-file "../hack/boilerplate.go.txt" --output-package "github.com/edgefarm/provider-nats/internal/clientset" --input-base "github.com/edgefarm/provider-nats/apis" --output-base "../tmp-clientgen" --input "stream/v1alpha1,consumer/v1alpha1"
//go:generate cp -r ../tmp-clientgen/github.com/edgefarm/provider-nats/internal/clientset ../internal/clientset
//go:generate rm -rf ../tmp-clientgen

package apis

import (
	_ "github.com/crossplane/crossplane-tools/cmd/angryjet" //nolint:typecheck
	_ "k8s.io/code-generator"                               //nolint:typecheck
	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"     //nolint:typecheck
)
