apiVersion: nats.crossplane.io/v1alpha1
kind: Stream
metadata:
  name: main-acc2
spec:
  forProvider:
    config:
      subjects:
        - main.>
      retention: Limits
      storage: File
      maxBytes: 102400
      discard: Old
  providerConfigRef:
    name: acc2
