apiVersion: nats.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-creds
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-creds
type: Opaque
data:
  credentials: ew0KICAiand0IjogImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSmxaREkxTlRFNUxXNXJaWGtpZlEuZXlKcWRHa2lPaUpDUmpSUVFrbEdXa1ZMUmxwR1YwUlBNekkyV0ZwTFUwbFdObGhQTTBkU1FsbFJOVUpTTWxOWE5FaFJWRUpEVFZSTFVsaFJJaXdpYVdGMElqb3hOamN6T0RjeU5qQTVMQ0pwYzNNaU9pSkJSRTlIV0ZVMVZUTTBUVE5QUmpkR1VsTklSVVpQU2s1RU1qSXpXa1ZIU1VWUE4wbzNObEJVVURSV05sTkZVMVJNTWtwQlRGVTBWU0lzSW01aGJXVWlPaUoxYzJWeUlpd2ljM1ZpSWpvaVZVSlhTRVJXTjBJM016TklOVFpPUkZnelVWRkJTMHRWU2tFM1JrOVhTVTVMV2tGSlF6ZERTRll6VWxWWVNVcFJUVVJITlVaVlJrZ2lMQ0p1WVhSeklqcDdJbkIxWWlJNmUzMHNJbk4xWWlJNmUzMHNJbk4xWW5NaU9pMHhMQ0prWVhSaElqb3RNU3dpY0dGNWJHOWhaQ0k2TFRFc0luUjVjR1VpT2lKMWMyVnlJaXdpZG1WeWMybHZiaUk2TW4xOS5VMlNXQ21WWjIzdU9XSjkzUURzRnNJVjBqUVBwR0VldWdyY3p5V0EzTUN6UFJXRGhqbVh0aXJ3SHQ5bWEwN0luOHB4bUk3VmRMLXRMV2lyclAzWHVEZyIsDQogICJzZWVkX2tleSI6ICJTVUFLN1Q3M1ZHUk5JWFRQQlozRkRWMjNRRlI0NDZaM0VJQkVGS0lSNEFOSERMM1pXNEpTNU1HRkpRIiwNCiAgImFkZHJlc3MiOiAibmF0czovL25hdHMubmF0cy5zdmM6NDIyMiINCn0=
# The `credentials` field in the secret of the provider is a base64 encoded JSON object with the following fields.

# - jwt: the NATS user's JWT
# - seed_key: the NATS user's seed key
# - address: the address of the NATS server

# Example:

# ```json
# {
#   "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJCRjRQQklGWkVLRlpGV0RPMzI2WFpLU0lWNlhPM0dSQllRNUJSMlNXNEhRVEJDTVRLUlhRIiwiaWF0IjoxNjczODcyNjA5LCJpc3MiOiJBRE9HWFU1VTM0TTNPRjdGUlNIRUZPSk5EMjIzWkVHSUVPN0o3NlBUUDRWNlNFU1RMMkpBTFU0VSIsIm5hbWUiOiJ1c2VyIiwic3ViIjoiVUJXSERWN0I3MzNINTZORFgzUVFBS0tVSkE3Rk9XSU5LWkFJQzdDSFYzUlVYSUpRTURHNUZVRkgiLCJuYXRzIjp7InB1YiI6e30sInN1YiI6e30sInN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsInR5cGUiOiJ1c2VyIiwidmVyc2lvbiI6Mn19.U2SWCmVZ23uOWJ93QDsFsIV0jQPpGEeugrczyWA3MCzPRWDhjmXtirwHt9ma07In8pxmI7VdL-tLWirrP3XuDg",
#   "seed_key": "SUAK7T73VGRNIXTPBZ3FDV23QFR446Z3EIBEFKIR4ANHDL3ZW4JS5MGFJQ",
#   "address": "nats://nats.nats.svc:4222"
# }
# This is how the json object is encoded in base64:
# ```
# $ echo '{
#   "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJCRjRQQklGWkVLRlpGV0RPMzI2WFpLU0lWNlhPM0dSQllRNUJSMlNXNEhRVEJDTVRLUlhRIiwiaWF0IjoxNjczODcyNjA5LCJpc3MiOiJBRE9HWFU1VTM0TTNPRjdGUlNIRUZPSk5EMjIzWkVHSUVPN0o3NlBUUDRWNlNFU1RMMkpBTFU0VSIsIm5hbWUiOiJ1c2VyIiwic3ViIjoiVUJXSERWN0I3MzNINTZORFgzUVFBS0tVSkE3Rk9XSU5LWkFJQzdDSFYzUlVYSUpRTURHNUZVRkgiLCJuYXRzIjp7InB1YiI6e30sInN1YiI6e30sInN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsInR5cGUiOiJ1c2VyIiwidmVyc2lvbiI6Mn19.U2SWCmVZ23uOWJ93QDsFsIV0jQPpGEeugrczyWA3MCzPRWDhjmXtirwHt9ma07In8pxmI7VdL-tLWirrP3XuDg",
#   "seed_key": "SUAK7T73VGRNIXTPBZ3FDV23QFR446Z3EIBEFKIR4ANHDL3ZW4JS5MGFJQ",
#   "address": "nats://nats.nats.svc:4222"
# }' | base64
