apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-creds
type: Opaque
data:
  credentials: ewogICJqd3QiOiAiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKbFpESTFOVEU1TFc1clpYa2lmUS5leUpxZEdraU9pSklRMFZDVlZnME5WYzBNMGhZUWt0Q1RWcEVVamRWVmpKVlNsTXlRa3BOVFVkTFN6WXpWVVJNUmtwSVFsUkdSMUpRUkRaQklpd2lhV0YwSWpveE5qSTVOekk0TWpFekxDSnBjM01pT2lKQlExSldXRE5hTlVSWVFqYzJORWRYVURNM1FWQmFUVUZXVVVSUVIwdFNWVWxXVVRVeldVYzFTVkZZUzBSQ1RVRTJOMVpQUTFWR1NTSXNJbTVoYldVaU9pSnVaM013TURBMFgzVnpaWElpTENKemRXSWlPaUpWUkZKRU5VSTFRa3RaVWs5WlNWQldVbG8wV2xsQlYxUlhNa3N5U1VaTFNWaEpWRmhYUVV4VlFsUmFRMVpNU1RWUlRrTXpOVkpSUnlJc0ltNWhkSE1pT25zaWNIVmlJanA3ZlN3aWMzVmlJanA3ZlN3aWMzVmljeUk2TFRFc0ltUmhkR0VpT2kweExDSndZWGxzYjJGa0lqb3RNU3dpZEhsd1pTSTZJblZ6WlhJaUxDSjJaWEp6YVc5dUlqb3lmWDAudW5PQklVbnRCMFcwX3dwZjVpdEp5bE4wUHc5cWFRSmVReVRGcmZzY3JWSXdDT2stUC1NRGNsZGptS01NVjd4ZFFrUDFGUXltVWxIUElTZ096MHVOQUEiLAogICJzZWVkX2tleSI6ICJTVUFCWVpDUzdCQVBBUDNBN0lDWExOSEhKVFdLRElJNjIzWFk0REVIVkNFQUlZQk9WRDVJUFJFNklZIiwKICAiYWRkcmVzcyI6ICJ0bHM6Ly9jb25uZWN0Lm5ncy5nbG9iYWw6NDIyMiIKfQo=
