apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nats
  annotations:
    meta.crossplane.io/maintainer: Armin Schlegel <armin.schlegel@gmx.de>
    meta.crossplane.io/source: github.com/edgefarm/provider-nats
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The NATS Crossplane provider adds support for
      managing NATS resources like jetstreams in Kubernetes.
spec:
  controller:
    image: ghcr.io/edgefarm/provider-nats-controller:VERSION
